[package]
name = "hwt"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
either = "1.5.1"

[dev-dependencies]
criterion = "0.2.10"
rand = "0.6.5"

[[bench]]
name = "benches"
harness = false
